Library Reservation Rooms
Vacansee/app pull request #71
Opened 2024-04-13 03:14 UTC by shamikkarkhanis

Functionality to view library study room reservations from within the app once data is uploaded. This framework can be applied to other rooms as well.

2024-04-13 03:16 UTC, shamikkarkhanis commented
fixed issues with "library study rooms" PR. This should be able to merge hassle free.

2024-04-16 23:33 UTC, paulbruzzi commented
Currently waiting on floorplans to be pushed to dev

2024-04-18 18:45 UTC, paulbruzzi requested changes
As of right now you can only reserve rooms on the 4th floor, and only some of them. Also all the links to the library booking site are broken.

2024-04-19 01:32 UTC, paulbruzzi approved these changes

2024-04-19 01:34 UTC, merged